server:
  port: 8081
resilience4j:
  circuitbreaker:
    instances:
      currency-cb-01:
        slidingWindowSize: 11
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
